# Generated by Django 2.0.4 on 2018-04-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ФИО')),
                ('number', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Номер')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рост')),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вес')),
                ('hand', models.SmallIntegerField(choices=[(1, 'Неизвестно'), (2, 'Правша'), (3, 'Левша'), (4, 'Обе руки')], default=1, verbose_name='Рука')),
                ('vk_id', models.URLField(blank=True, max_length=300, null=True, unique=True, verbose_name='Страница VK')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Email')),
                ('phone', models.TextField(blank=True, max_length=15, null=True, unique=True, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['name', 'team', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название')),
                ('team_description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['team_name'],
            },
        ),
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.Teams'),
        ),
    ]
